"""Los eventos del board de Miro, tal como los declararon los 9 equipos.

Fuente: "Mi primer tablero" (Miro), acordado entre los equipos. El board fija
que los nombres van **en ingles y camelCase**.

Se transcriben **tal cual**, con typos incluidos. Corregirlos aca serviria de
poco: si un equipo publica `streetClousureEnded` y el Core espera
`streetClosureEnded`, el evento no encuentra destino igual. Dejandolos como
estan, el hub los recibe y el dashboard los marca en las alertas de
integracion, que es donde los equipos los van a ver y acordar.

Ver `MISMATCHES` al final: son las desalineaciones detectadas al transcribir.
"""

from __future__ import annotations

# Cada modulo: (nombre, display, equipo, publica, consume)
MODULES: list[tuple[str, str, str, list[str], list[str]]] = [
    (
        "ciudadanos",
        "Ciudadanos, Organizaciones y Expedientes digitales",
        "Equipo 1",
        [
            "citizenRegistered",
            "citizenUpdated",
            "citizenBlocked",
            "citizenDeceased",
            "addressUpdated",
            "organizationRegistered",
            "representationGranted",
            "representationExpired",
            "updateTicketStatus",
            "citizenInfoDelivered",
            "organizationInfoDelivered",
            "socialDocumentationDelivered",
            "caseFileResolved",
        ],
        [
            "ticketCreated",
            "ticketUpdated",
            "publicWorksProjectApproved",
            "publicWorksProjectCompleted",
            "permitApplicationStarted",
            "permitDocumentationReviewed",
            "inspectionUpdate",
            "paymentPlanRequested",
            "exemptionRequested",
            "paymentUpdated",
            "exemptionUpdated",
            "socialBenefitUpdated",
            "socialDocumentationRequested",
            "infractionAppealed",
        ],
    ),
    (
        "atencion-ciudadana",
        "Atencion Ciudadana",
        "Equipo 2",
        ["ticketCreated", "ticketUpdated"],
        ["citizenRegistered", "citizenUpdated", "updateTicketStatus"],
    ),
    (
        "obras",
        "Obras Publicas e Infraestructura",
        "Equipo 3",
        [
            "publicWorksProjectApproved",
            "publicWorksProjectCompleted",
            "updateTicketStatus",
            "workOrderScheduled",
            "workOrderCompleted",
            "streetClosureRequested",
        ],
        [
            "caseFileResolved",
            "ticketCreated",
            "ticketUpdated",
            "infrastructureRepairRequested",
            "containerDamaged",
            "treeRiskDetected",
            "streetClosureApproved",
            "streetClosureRejected",
            "streetClosureEnded",
            "roadAccidentRegistered",
        ],
    ),
    (
        "habilitaciones",
        "Habilitaciones, Inspecciones y Control Comercial",
        "Equipo 4",
        [
            "permitApplicationStarted",
            "permitDocumentationReviewed",
            "permitUpdate",
            "inspectionUpdate",
            "closureUpdate",
            "permitFeeGenerated",
            "commercialFineGenerated",
            "ticketInProgress",
        ],
        [
            "organizationRegistered",
            "representationGranted",
            "paymentRegistered",
            "debtSettled",
            "ticketUpdated",
            "envirometnalViolationDetected",
        ],
    ),
    (
        "rentas",
        "Rentas, tributos, deudas y planes de pago",
        "Equipo 5",
        [
            "debtOverdue",
            "paymentRegistered",
            "paymentReversed",
            "debtSettled",
            "paymentPlanRequested",
            "paymentPlanGranted",
            "paymentPlanRejected",
            "exemptionRequested",
            "exemptionApproved",
            "exemptionRejected",
            "updateTicketStatus",
        ],
        [
            "citizenRegistered",
            "citizenUpdated",
            "citizenBlocked",
            "citizenDeceased",
            "organizationRegistered",
            "representationGranted",
            "representationExpired",
            "infractionConfirmed",
            "socialBenefitUpdated",
            "permitFeeGenerated",
            "commercialFineGenerated",
            "permitUpdate",
            "ticketCreated",
            "ticketUpdated",
        ],
    ),
    (
        "ambiente",
        "Ambiente e Higiene",
        "Equipo 6",
        [
            "urbanServiceScheduled",
            "urbanServiceStarted",
            "urbanServiceDelayed",
            "urbanServiceCompleted",
            "containerOverflow",
            "containerDamaged",
            "treeRiskDetected",
            "treePruningScheduled",
            "enviromentalInspectionScheduled",
            "enviromentalInspectionCompleted",
            "envirometnalViolationDetected",
            "infrastructureRepairRequested",
            "streetClosureRequested",
            "zoneNotServiced",
        ],
        [
            "ticketCreated",
            "ticketUpdated",
            "workOrderCompleted",
            "workOrderScheduled",
            "commercialFineIssued",
            "closureOrdered",
            "violationDismissed",
            "streetClosureApproved",
            "streetClosureRejected",
            "streetClousureEnded",
            "citizenInfoDelivered",
            "organizationInfoDelivered",
        ],
    ),
    (
        "transito",
        "Transito, Estacionamiento y Seguridad Vial",
        "Equipo 7",
        [
            "infractionConfirmed",
            "infractionRegistered",
            "infractionAppealed",
            "infractionAnulled",
            "streetClosureApproved",
            "streetClosureRejected",
            "streetClousureEnded",
            "roadAccidentRegistered",
            "trafficOperationCreated",
            "vehicleImpounded",
            "vehicleReleased",
            "updateTicketStatus",
        ],
        [
            "streetClosureRequested",
            "urbanServiceScheduled",
            "treeRiskDetected",
            "treePruningScheduled",
            "workOrderScheduled",
            "workOrderCompleted",
            "ticketUpdated",
            "paymentRegistered",
            "debtSettled",
            "paymentReversed",
        ],
    ),
    (
        "desarrollo-social",
        "Desarrollo Social, salud comunitaria y beneficios",
        "Equipo 8",
        [
            "socialDocumentationRequested",
            "socialBenefitUpdated",
            "updateTicketStatus",
        ],
        [
            "citizenRegistered",
            "addressUpdated",
            "overdueDebt",
            "debtSettled",
            "exemptionApproved",
            "exemptionRejected",
            "ticketUpdated",
            "socialDocumentationDelivered",
        ],
    ),
    (
        "core",
        "Core - Pasamanos de eventos",
        "Equipo 9",
        ["eventProcessingFailed", "eventRejected"],
        ["eventProcessingFailed"],
    ),
]

# Descripciones de los eventos mas cruzados, para que el dashboard no muestre
# solo nombres pelados.
DESCRIPTIONS: dict[str, str] = {
    "citizenRegistered": "Se registro un ciudadano nuevo.",
    "citizenUpdated": "Cambiaron los datos de un ciudadano.",
    "citizenBlocked": "Un ciudadano quedo bloqueado.",
    "citizenDeceased": "Se registro el fallecimiento de un ciudadano.",
    "addressUpdated": "Cambio el domicilio de un ciudadano.",
    "organizationRegistered": "Se registro una organizacion, empresa o comercio.",
    "representationGranted": "Se otorgo una representacion sobre una organizacion.",
    "representationExpired": "Vencio una representacion.",
    "caseFileResolved": "Se resolvio un expediente digital.",
    "ticketCreated": "Un vecino presento un reclamo, solicitud o denuncia.",
    "ticketUpdated": "Cambio el estado de un reclamo.",
    "updateTicketStatus": "Un area operativa informa el avance de un reclamo.",
    "ticketInProgress": "Un reclamo paso a en curso.",
    "publicWorksProjectApproved": "Se aprobo un proyecto de obra publica.",
    "publicWorksProjectCompleted": "Se termino un proyecto de obra publica.",
    "workOrderScheduled": "Se programo una orden de trabajo.",
    "workOrderCompleted": "Se finalizo una orden de trabajo.",
    "streetClosureRequested": "Un area pide cerrar una calle.",
    "streetClosureApproved": "Transito autorizo un corte de calle.",
    "streetClosureRejected": "Transito rechazo un corte de calle.",
    "streetClosureEnded": "Termino un corte de calle.",
    "streetClousureEnded": "Termino un corte de calle. (nombre con typo del board)",
    "roadAccidentRegistered": "Se registro un accidente vial.",
    "permitApplicationStarted": "Se inicio una solicitud de habilitacion.",
    "permitDocumentationReviewed": "Se reviso la documentacion de una habilitacion.",
    "permitUpdate": "Cambio el estado de una habilitacion.",
    "inspectionUpdate": "Cambio el estado de una inspeccion.",
    "closureUpdate": "Se dispuso o se levanto una clausura.",
    "permitFeeGenerated": "Se genero la tasa de una habilitacion.",
    "commercialFineGenerated": "Se genero una multa comercial.",
    "commercialFineIssued": "Se genero una multa comercial. (nombre alternativo del board)",
    "closureOrdered": "Se dispuso una clausura.",
    "violationDismissed": "Se desestimo una infraccion comercial.",
    "debtOverdue": "Una deuda quedo vencida.",
    "overdueDebt": "Una deuda quedo vencida. (nombre alternativo del board)",
    "paymentRegistered": "Se registro un pago.",
    "paymentReversed": "Se revirtio un pago.",
    "paymentUpdated": "Cambio el estado de un pago.",
    "debtSettled": "Se cancelo una deuda.",
    "paymentPlanRequested": "Se solicito un plan de pago.",
    "paymentPlanGranted": "Se otorgo un plan de pago.",
    "paymentPlanRejected": "Se rechazo un plan de pago.",
    "exemptionRequested": "Se solicito una exencion.",
    "exemptionApproved": "Se aprobo una exencion.",
    "exemptionRejected": "Se rechazo una exencion.",
    "exemptionUpdated": "Cambio el estado de una exencion.",
    "urbanServiceScheduled": "Se programo un servicio urbano.",
    "urbanServiceStarted": "Empezo un servicio urbano.",
    "urbanServiceDelayed": "Un servicio urbano se demoro.",
    "urbanServiceCompleted": "Se completo un servicio urbano.",
    "containerOverflow": "Un contenedor se desbordo.",
    "containerDamaged": "Un contenedor esta danado.",
    "treeRiskDetected": "Se detecto un arbol con riesgo.",
    "treePruningScheduled": "Se programo una poda.",
    "zoneNotServiced": "Una zona quedo sin atender.",
    "enviromentalInspectionScheduled": (
        "Se programo una inspeccion ambiental. (el board escribe 'enviromental')"
    ),
    "enviromentalInspectionCompleted": (
        "Se completo una inspeccion ambiental. (el board escribe 'enviromental')"
    ),
    "envirometnalViolationDetected": (
        "Se detecto un incumplimiento ambiental. (el board escribe 'envirometnal')"
    ),
    "infrastructureRepairRequested": "Se pidio una reparacion de infraestructura.",
    "infractionRegistered": "Se registro una infraccion de transito.",
    "infractionConfirmed": "Una infraccion quedo firme.",
    "infractionAppealed": "Se presento un descargo sobre una infraccion.",
    "infractionAnulled": "Se anulo una infraccion.",
    "trafficOperationCreated": "Se creo un operativo de transito.",
    "vehicleImpounded": "Se retuvo un vehiculo.",
    "vehicleReleased": "Se libero un vehiculo retenido.",
    "socialBenefitUpdated": "Cambio el estado de un beneficio social.",
    "socialDocumentationRequested": "Se pidio documentacion social.",
    "socialDocumentationDelivered": "Se entrego documentacion social.",
    "citizenInfoDelivered": "Se entregaron datos de un ciudadano.",
    "organizationInfoDelivered": "Se entregaron datos de una organizacion.",
    "eventProcessingFailed": "El Core no pudo procesar un evento.",
    "eventRejected": "El Core rechazo un evento por estructura invalida.",
}

MISMATCHES: list[tuple[str, str, str]] = [
    (
        "debtOverdue",
        "overdueDebt",
        "rentas publica 'debtOverdue' y desarrollo-social consume 'overdueDebt'.",
    ),
    (
        "streetClosureEnded",
        "streetClousureEnded",
        "transito publica 'streetClousureEnded' (con typo) y obras consume "
        "'streetClosureEnded'. ambiente tambien consume el nombre con typo.",
    ),
    (
        "commercialFineGenerated",
        "commercialFineIssued",
        "habilitaciones publica 'commercialFineGenerated' y ambiente consume "
        "'commercialFineIssued'.",
    ),
    (
        "closureUpdate",
        "closureOrdered / violationDismissed",
        "habilitaciones publica un solo 'closureUpdate' con estados, y ambiente "
        "espera dos eventos separados.",
    ),
    (
        "environmentalInspectionScheduled",
        "enviromentalInspectionScheduled",
        "ambiente escribe 'enviromental' y 'envirometnal' (dos typos distintos) en "
        "sus propios eventos.",
    ),
    (
        "notificationSent / notificationFailed",
        "(sin productor)",
        "rentas y desarrollo-social los declaran como consumidos, pero los publicaba "
        "el modulo de notificaciones del Core, que se saco del alcance. Hoy nadie "
        "los publica.",
    ),
]
